#!/bin/bash
# scripts/config-sync.sh
# Reads devstarter-config.yml and regenerates .project.env
# Usage: bash scripts/config-sync.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
CONFIG="$ROOT/devstarter-config.yml"
ENV_OUT="$ROOT/.project.env"

if [[ ! -f "$CONFIG" ]]; then
  echo "Error: devstarter-config.yml not found at $CONFIG" >&2
  exit 1
fi

# Extract a value from a YAML section: get_val <section> <key>
get_val() {
  awk -v section="$1:" -v key="  $2:" '
    /^[a-z_]+:/ { in_section = ($0 == section) }
    in_section && index($0, key) == 1 {
      sub(/^[^:]+: */, ""); gsub(/"/, ""); gsub(/ *#.*/, ""); sub(/ +$/, ""); print; exit
    }
  ' "$CONFIG"
}

# Read all fields
VCS_TYPE=$(get_val vcs type)
VCS_REPO=$(get_val vcs repo)
VCS_SECONDARY_1=$(get_val vcs secondary_1)
VCS_SECONDARY_2=$(get_val vcs secondary_2)
VCS_SYNC=$(get_val vcs sync_branches)
BRANCH_STRATEGY=$(get_val vcs branch_strategy)
MAIN_BRANCH=$(get_val vcs main_branch)
DEV_BRANCH=$(get_val vcs dev_branch)
PM_TYPE=$(get_val pm type)
NOTION_DB=$(get_val pm notion_database_id)
NOTION_URL=$(get_val pm notion_board_url)
CI_TYPE=$(get_val ci type)
SECRETS_BACKEND=$(get_val secrets backend)
AI_PROVIDER=$(get_val ai provider)
PROJECT_TYPE=$(get_val project type)
LANGUAGE=$(get_val project language)

# Repo env var name depends on VCS type
case "$VCS_TYPE" in
  github) REPO_VAR="GITHUB_REPO" ;;
  gitlab) REPO_VAR="GITLAB_REPO" ;;
  *)      REPO_VAR="VCS_REPO" ;;
esac

# Write .project.env
{
cat << EOF
# .project.env — AUTO-GENERATED from devstarter-config.yml
# ⚠️  Do NOT edit this file directly.
# ⚠️  Edit devstarter-config.yml instead — .project.env is auto-synced.
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# VERSION CONTROL
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
VCS_TYPE=${VCS_TYPE}
${REPO_VAR}=${VCS_REPO}

VCS_SECONDARY_1=${VCS_SECONDARY_1}
VCS_SECONDARY_2=${VCS_SECONDARY_2}
VCS_SYNC_BRANCHES=${VCS_SYNC}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# BRANCHING STRATEGY
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BRANCH_STRATEGY=${BRANCH_STRATEGY}
MAIN_BRANCH=${MAIN_BRANCH}
DEV_BRANCH=${DEV_BRANCH}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PROJECT MANAGEMENT
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PM_TYPE=${PM_TYPE}
EOF

# Notion fields only when PM is notion
if [[ "$PM_TYPE" == "notion" && -n "$NOTION_DB" ]]; then
cat << EOF
NOTION_DATABASE_ID=${NOTION_DB}
NOTION_BOARD_URL=${NOTION_URL}
EOF
fi

cat << EOF

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# CI/CD
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CI_TYPE=${CI_TYPE}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SECRETS BACKEND
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
SECRETS_BACKEND=${SECRETS_BACKEND}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# AI PROVIDER
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
AI_PROVIDER=${AI_PROVIDER}

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PROJECT TYPE
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
PROJECT_TYPE=${PROJECT_TYPE}
LANGUAGE=${LANGUAGE}
EOF
} > "$ENV_OUT"

echo "✓ .project.env synced from devstarter-config.yml"
